"""Service package entrypoint.

`_version.py` is generated by the `hatch` build hook (see pyproject.toml's
`tool.hatch.build.hooks.version` block) and is gitignored. It only exists
when the package is built or installed from source; the Databricks Apps
deploy syncs source files (not built artifacts) so `_version.py` won't be
present at runtime. Fall back gracefully — `__version__` is metadata, not
load-bearing.
"""
try:
    from ._version import version as __version__
except ModuleNotFoundError:
    __version__ = "0.0.0+source"
